FROM debian:latest
#ADD ./src ./
#WORKDIR /src

# Update
RUN apt-get update
#RUN apt-get install -y apt-utils
RUN apt-get -f -y dist-upgrade

# Generic Packages
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ferm apt-utils
RUN apt-get install -y dpkg deborphan file lsof sysfsutils screen bc debsums debian-goodies htop psmisc less mlocate bash-completion sudo colordiff python-optcomplete vim vim-scripts strace tmux ltrace bzip2 dmidecode sysstat lsb-release
# Network related packages
RUN apt-get install -y mtr-tiny curl net-tools exim4 dnsutils monit iftop rsync bind9-host tcpdump telnet rkhunter chkrootkit lldpd vlan lftp whois bind9utils ethtool ifenslave-2.6 bridge-utils bwm-ng ndisc6

# Cleanup
RUN apt-get autoremove -y --purge
RUN while [ "$(deborphan -n | wc -l)" -gt 0  ] ; do apt-get purge -y $(deborphan -n); done
RUN apt-get autoremove -y --purge
RUN apt-get clean
RUN updatedb

#EXPOSE 8000

#CMD [ "test1", "test2" ]
